FROM python:3.10.8-alpine

WORKDIR /usr/src/app

COPY ./requirements/env.txt ./
RUN pip install --no-cache-dir -r env.txt

COPY ./chat/ .

CMD [ "uvicorn", "main:app", "--port", "8001" , "--log-level", "debug", "--host", "0.0.0.0"]     
