FROM python:3.10.8-alpine

WORKDIR /usr/src/app

COPY ./requirements/env.txt ./
RUN pip install --no-cache-dir -r env.txt

COPY ./auth/ .

CMD [ "uvicorn", "auth.main:app", "--port", "8002" , "--log-level", "debug", "--host", "0.0.0.0"]     
