"""initial

Revision ID: 3e651fcf9a2a
Revises: 
Create Date: 2022-10-30 22:05:12.996634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e651fcf9a2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("create schema authentication")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    schema='authentication'
    )
    op.create_table('login_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_data_id', sa.Integer(), nullable=True),
    sa.Column('fingerprint', sa.String(length=256), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('response', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['login_data_id'], ['authentication.login_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='authentication'
    )
    op.create_table('login_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login_data_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('stopped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['login_data_id'], ['authentication.login_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='authentication'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_session', schema='authentication')
    op.drop_table('login_attempt', schema='authentication')
    op.drop_table('login_data', schema='authentication')
    # ### end Alembic commands ###
    op.execute("drop schema authentication")
