FROM python:3.10.8-alpine

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./src/ .

CMD [ "uvicorn", "main:app", "--port", "8002" , "--log-level", "debug", "--host", "0.0.0.0"]     
